Login/Controllers/LoginController.cs
using WebDBApp.Database;
using WebDBApp.Extensions;
using WebDBApp.Helpers;
using WebDBApp.Interfaces;
using WebDBApp.Models;
using WebDBApp.ViewModels;
using NLog;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI;

namespace WebDBApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private static Logger logger = LogManager.GetCurrentClassLogger();
        private readonly IHashHelper _hashHelper;

        public LoginController(IUnitOfWork unitOfWork,  IHashHelper hashHelper)
        {
            _unitOfWork = unitOfWork;
            _hashHelper = hashHelper;
            //logger.Trace("Sample trace message");
            //logger.Debug("Sample debug message");
            //logger.Info("Sample informational message");
            //logger.Warn("Sample warning message");
            //logger.Error("Sample error message");
            //logger.Fatal("Sample fatal error message");
        }

        [HttpGet]
        public ActionResult Index()
        {
            this.Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            this.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            this.Response.Cache.SetNoStore();

            return View(new User());
        }

        [HttpGet]
        public ActionResult IndexPartial()
        {
            return PartialView("~/Views/Login/Index.cshtml");
        }

        [HttpPost]
        public ActionResult Login(string login, string password)
        {
            using (var dbContext = new AppDbContext())
            {
                var user = _unitOfWork.UserRepository.All().FirstOrDefault(usr => usr.Login == login && !usr.IsFrozen);
                if (user == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("~/Views/PartialViews/Error.cshtml", "Niepoprawny login lub hasło, bądź konto jest zamrożone");
                }
                if (!string.Equals(_hashHelper.Compute(password, user.Salt), user.Password))
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("~/Views/PartialViews/Error.cshtml", "Niepoprawny login lub hasło, bądź konto jest zamrożone.");
                }
                
                FormsAuthentication.SetAuthCookie(user.Login, false);
                SessionHelper.SetLogin(user.Login,user.Role.Name);
                return new EmptyResult();
            }
        }

        [HttpGet]
        public ActionResult Logout()
        {
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View("~/Views/Login/Register.cshtml", new RegisterAccountViewModel());
        }

        [HttpPost]
        public ActionResult Register(RegisterAccountViewModel viewModel)
        {
            try
            {
                var role = _unitOfWork.RoleRepository.Find("Użytkownik");
                _unitOfWork.UserRepository.Add(viewModel,role);
                
                EmailHelper.SendEmail(new EmailAccount()
                {
                    Email = viewModel.Email,
                    Subject = "Rejestracja nowego konta",
                    Request = EmailHelper.GetNewAccountCreatedMessage(viewModel)
                });

                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                logger.Error(e, e.Message);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("~/Views/PartialViews/Error.cshtml", e.Message);
            }
            
        }

        [HttpGet]
        public ActionResult ResetPassword()
        {
            return View("~/Views/Login/ResetPassword.cshtml");
        }

        [HttpPost]
        public ActionResult ResetPassword(ResetPasswordRequestViewModel resetRequest)
        {
            try
            {
                resetRequest.Date = DateTime.Now;
                _unitOfWork.UserRepository.ResetPassword(resetRequest);
                _unitOfWork.SaveChanges();               
                return PartialView("~/Views/Login/Index.cshtml");
            }
            catch(Exception e)
            {
                logger.Error(e, e.Message);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("~/Views/PartialViews/Error.cshtml", e.Message);
            }            
        }                

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public JsonResult IsEmail_Available(string email)
        {
            if (!_unitOfWork.UserRepository.All().Any(user => user.Email == email))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }              

            string suggestedEmail = String.Format(CultureInfo.InvariantCulture,
                "{0} jest niedostępny.", email);

            return Json(suggestedEmail, JsonRequestBehavior.AllowGet);
        }

        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
        public JsonResult IsLogin_Available(string login)
        {
            if (!_unitOfWork.UserRepository.All().Any(user => user.Login == login))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            string suggestedLogin = String.Format(CultureInfo.InvariantCulture,
                "{0} jest niedostępny.", login);

            Random rnd = new Random();
            for (int i = 1; i < 100; i++)
            {
                string altCandidate = login + rnd.Next(i, i + 1000).ToString();
                if (!_unitOfWork.UserRepository.All().Any(user => user.Login == altCandidate))
                {
                    suggestedLogin = String.Format(CultureInfo.InvariantCulture,
                   "{0} jest niedostępny. Spróbuj {1}.", login, altCandidate);
                    break;
                }
            }
            return Json(suggestedLogin, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

Login/Controllers/OrderController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebDBApp.Enum;
using WebDBApp.Helpers;
using WebDBApp.Interfaces;
using WebDBApp.Service_References.Annotation;
using WebDBApp.ViewModels;

namespace Login.Controllers
{
    public class OrderController : Controller
    {

        private static Logger logger = LogManager.GetCurrentClassLogger();
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var viewModel = new OrderViewModel(_unitOfWork);

            viewModel.SetOrders(false);//All awaiting orders

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult OrdersForUser()
        {
            var viewModel = new OrderViewModel(_unitOfWork);
            var login = SessionHelper.GetElement<string>(SessionElement.Login);
            var user = _unitOfWork.UserRepository.Find(login);

            viewModel.SetOrdersforUser(user);//All orders for current user

            return View("~/Views/Order/Index.cshtml",viewModel);
        }

        [HttpGet]
        [CheckSession(Role = new string[] { "Organizator" })]
        public ActionResult NewOrder()
        {
            var viewModel = new NewOrderViewModel();

            viewModel.SelectedBuilding = 0;
            viewModel.Buildings = _unitOfWork.BuildingRepository.All();
            return View(viewModel);
        }
        
        [CheckSession(Role = new string[] { "Administrator" })]
        public ActionResult AcceptOrder(int id)
        {
            var order = _unitOfWork.OrderRepository.Find(id);
            order.OrderDetails.IsCompleted = true;

            _unitOfWork.SaveChanges();

            return RedirectToAction("Index");
        }

        [CheckSession(Role = new string[] { "Administrator" })]
        public ActionResult RejectOrder(int id)
        {
            var order = _unitOfWork.OrderRepository.Find(id);
            
            order.OrderDetails.IsRejected = true;

            _unitOfWork.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult NewOrder(NewOrderViewModel viewModel)
        {
            try
            {
                var login = SessionHelper.GetElement<string>(SessionElement.Login);
                _unitOfWork.OrderRepository.Add(new WebDBApp.Models.Order
                {
                    User = _unitOfWork.UserRepository.Find(login),
                    Date = DateTime.Now,
                    Title = viewModel.Title,
                    OrderDetails = new WebDBApp.Models.OrderDetails
                    {
                        Amount = viewModel.Amount,
                        Description = viewModel.Description,

                    },
                    Building = _unitOfWork.BuildingRepository.Find(viewModel.SelectedBuilding),
                    Room = _unitOfWork.RoomRepository.Find(viewModel.SelectedRoom)
                });

                _unitOfWork.SaveChanges();
            }
            catch (Exception ex)
            {
                logger.Error(ex, ex.Message);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("~/Views/PartialViews/Error.cshtml", ex.Message);
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        [CheckSession(Role = new string[] { "Organizator" })]
        public ActionResult EditOrder(int id)
        {
            var viewModel = new NewOrderViewModel();
            var order = _unitOfWork.OrderRepository.Find(id);

            viewModel.Buildings = _unitOfWork.BuildingRepository.All();
            viewModel.ID = order.ID;
            viewModel.Title = order.Title;
            viewModel.Description = order.OrderDetails.Description;
            viewModel.Amount = order.OrderDetails.Amount;
            viewModel.SelectedBuilding = order.Building.ID;
            viewModel.SelectedRoom = order.Room.ID;

            return View(viewModel);
        }

        [HttpPost]
        [CheckSession(Role = new string[] { "Organizator" })]
        public ActionResult EditOrder(NewOrderViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var order = _unitOfWork.OrderRepository.Find(viewModel.ID);

                order.Title = viewModel.Title;
                order.Date = DateTime.Now;
                order.OrderDetails.Amount = viewModel.Amount;
                order.OrderDetails.Description = viewModel.Description;
                order.OrderDetails.IsCompleted = false;
                order.OrderDetails.IsRejected = false;
                order.Building.ID = viewModel.SelectedBuilding;
                order.Room.ID = viewModel.SelectedRoom;


                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [HttpPost]
        [CheckSession(Role = new string[] { "Organizator" })]
        public ActionResult DeleteOrder(int id)
        {
            if (ModelState.IsValid)
            {
                var oldOrder = _unitOfWork.OrderRepository.Find(id);
                oldOrder.OrderDetails = null;
                oldOrder.Building = null;
                oldOrder.Room = null;
                _unitOfWork.OrderRepository.Remove(id);


                _unitOfWork.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

Login/Controllers/RoomController.cs
using WebDBApp.Service_References.Annotation;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDBApp.ViewModels;
using WebDBApp.Interfaces;
using System.Net;
using WebDBApp.Models;
using Newtonsoft.Json;

namespace WebDBApp.Controllers
{
    [SessionExpireFilter]
    public class RoomController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        private readonly IUnitOfWork _unitOfWork;

        public RoomController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var viewModel = new RoomViewModel(_unitOfWork);
            return View(viewModel);
        }

        [HttpGet]
        public string GetRoomsByBuilding(int id)
        {
            var rooms = _unitOfWork.BuildingRepository.Find(id).Rooms.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.ID.ToString()
            });

            var roomslist = new List<SelectListItem>();
            roomslist.AddRange(rooms);

            string json = JsonConvert.SerializeObject(roomslist);

            return json;
        }

        [HttpGet]
        [CheckSession(Role = new string[] { "Administrator" })]
        public ActionResult NewRoom()
        {
            var viewModel = new NewRoomViewModel();
            viewModel.Buildings = _unitOfWork.BuildingRepository.All();
            var x = viewModel.Buildings.Select(r => new SelectListItem
            {
                Text = r.BuildingDetails.Name,
                Value = r.ID.ToString()
            });
            viewModel.choices.AddRange(x);

            return View(viewModel);
        }

        [HttpPost]
        [CheckSession(Role = new string[] { "Administrator" })]
        public ActionResult NewRoom(NewRoomViewModel viewModel)
        {
            try
            {
                var room = new Room
                {
                    Name = viewModel.Name,
                    SurfaceArea = viewModel.SurfaceArea
                };
                var gym = _unitOfWork.BuildingRepository.Find(viewModel.SelectedBuilding);
                gym.Rooms.Add(room);

                _unitOfWork.SaveChanges();

            }
            catch (Exception ex)
            {
                logger.Error(ex, ex.Message);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return PartialView("~/Views/PartialViews/Error.cshtml", ex.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [CheckSession(Role = new string[] { "Administrator" })]
        public ActionResult EditRoom(int id)
        {
            var viewModel = new NewRoomViewModel();
            viewModel.Buildings = _unitOfWork.BuildingRepository.All();
            var x = viewModel.Buildings.Select(r => new SelectListItem
            {
                Text = r.BuildingDetails.Name,
                Value = r.ID.ToString()
            });
            viewModel.choices.AddRange(x);
            var room = _unitOfWork.RoomRepository.Find(id);
            viewModel.ID = room.ID;
            viewModel.Name = room.Name;
            viewModel.SurfaceArea = room.SurfaceArea;

            return View(viewModel);
        }

        [HttpPost]
        [CheckSession(Role = new string[] { "Administrator" })]
        public ActionResult EditRoom(NewRoomViewModel viewModel)
        {
            if (ModelState.IsValid)
            {             
                var building = _unitOfWork.BuildingRepository.All().First(g => g.ID == viewModel.SelectedBuilding);
                if (building.Rooms.Any(h => h.ID == viewModel.ID))
                {
                    var oldRoom = building.Rooms.First(room => room.ID == viewModel.ID);
                    oldRoom.Name = viewModel.Name;
                    oldRoom.SurfaceArea = viewModel.SurfaceArea;
                }
                else
                {
                    var Room = _unitOfWork.RoomRepository.All().First(d => d.ID == viewModel.ID);
                    Room.Building = null;
                    building.Rooms.Add(Room);
                }
                

                _unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [HttpPost]
        [CheckSession(Role = new string[] { "Administrator" })]
        public ActionResult DeleteRoom(int id)
        {
            if (ModelState.IsValid)
            {
                var oldRoom = _unitOfWork.RoomRepository.Find(id);
                
                oldRoom.Accessories = null;
                _unitOfWork.RoomRepository.Remove(id);


                _unitOfWork.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        
    }
}

Login/Views/Shared/_Layout.cshtml
@using WebDBApp.Helpers;
@using WebDBApp.Enum;
@{
    var role = SessionHelper.GetElement<string>(SessionElement.Role);
}
    <!DOCTYPE html>
    <html>
    <head>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <link href="~/Content/main.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/home.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/fullcalendar.min.css" rel="stylesheet" />

        <link href="~/Content/navbar.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css" rel="stylesheet" />
        <script src="~/Scripts/jquery-3.2.1.js"></script>
        <script src="~/Scripts/jquery-3.2.1.min.js"></script>
        <script src="~/Scripts/lib/jquery.min.js"></script>
        <script src="~/Scripts/lib/jquery-ui.min.js"></script>
        <script src="/Scripts/jquery.validate.min.js" type="text/javascript"></script>
        <script src="/scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
        <script src="~/Scripts/bootstrap.js"></script>
        <script src="~/Scripts/angular.min.js"></script>
        <script src="~/Scripts/angular-ui-router.min.js"></script>
        <script src="~/Scripts/moment-with-locales.min.js"></script>
        <script src="~/Scripts/fullcalendar.min.js"></script>
        <script src="~/Scripts/calendar/calendar.js"></script>
        <script src="~/Scripts/gcal.js"></script>
        <script src="~/Scripts/angular-ui/ui-bootstrap.min.js"></script>
        <script src="~/Scripts/moment.min.js"></script>
        <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
        <script src="~/Scripts/Login/main.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/js/bootstrap-dialog.min.js"></script>
        <title>@ViewBag.Title</title>
    </head>
    <body>
        @*@Html.ActionLink("MTAB", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <span class="navbar-brand">MTAB</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Home" )">
                        <span class="glyphicon glyphicon-home"></span>
                        Home
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Calendar" )">
                        <span class="glyphicon glyphicon-calendar"></span>
                        Scheduler
                    </a>
                </li>
                @*<li>
                    <a href="@Url.Action("Index", "Tests" )">
                        <span class="glyphicon glyphicon-scale"></span>
                        Test Yourself!
                    </a>
                </li>*@
                @if(role == "Organizator")
                {
                <li>
                    <button type="button" class="btn navbar-btn dropdown-toggle" data-toggle="dropdown" style="color: #000">Organizer
                        <span class="caret"></span>
                        <span class="sr-only"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="@Url.Action("NewEvent", "Calendar" )">
                                <span class="glyphicon glyphicon-bookmark"></span>
                                New Event
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("OwnerEvent", "Calendar" )">
                                <span class="glyphicon glyphicon-bookmark"></span>
                                Your Events
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("OrdersForUser", "Order" )">
                                <span class="glyphicon glyphicon-bookmark"></span>
                                My Orders
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("NewOrder", "Order" )">
                                <span class="glyphicon glyphicon-bookmark"></span>
                                New Order
                            </a>
                        </li>
                    </ul>  
                </li> 
                }
                else if(role =="Administrator") 
                {
                <li>
                    <button type="button" class="btn navbar-btn dropdown-toggle" data-toggle="dropdown"style="color: #000">Worker
                        <span class="caret"></span>
                        <span class="sr-only"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="@Url.Action("Index", "Order" )">
                                <span class="glyphicon glyphicon-bookmark"></span>
                                Orders
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Room" )">
                                <span class="glyphicon glyphicon-bookmark"></span>
                                Rooms
                            </a>
                        </li>
                    </ul>  
                </li> 
                }              
                
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="@Url.Action("Index", "Profile" )">
                        Your Meetings
                        <span class="glyphicon glyphicon-tent"></span>
                    </a>
                </li>
                @if(role == "Administrator")
                {
                     <li>
                         <a href="@Url.Action("Index", "Users" )">
                             User Managment
                             <span class="glyphicon glyphicon-cog"></span>
                         </a>
                     </li>
                }
                
                <li>
                    <a href="@Url.Action("Logout", "Login" )">
                        Log out
                        <span class="glyphicon glyphicon-log-out"></span>
                    </a>
                </li>
            </ul>
        </div>
        <div id="viewContent">
            <div class="row">
                <div class="col-md-6" style="float: none; margin: 0 auto;">
                    <div id="errorPlaceHolder"></div>
                </div>
            </div>
            @RenderBody()
        </div>
    </body>
</html>

Login/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/login.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/main.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/home.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" type="text/css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="/scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div id="viewContent">
        @RenderBody()
    </div>
    @Html.Partial("~/Views/PartialViews/Loading.cshtml")
    <script type="text/javascript" src="@Url.Content("/Scripts/Login/login.js")"></script>
    <script type="text/javascript" src="@Url.Content("/Scripts/Login/main.js")"></script>
</body>
</html>